image: maven:latest

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS verify site site:stage'

test:
  stage: test
  script:
  - mvn test
  - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' target/site/jacoco/jacoco.csv
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
